name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Hugo
        uses: peaceiris/hugo-actions@v3
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo

      - name: Deploy
        uses: actions/deploy-pages@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}