name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch the entire history for all branches

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.112.0'  # Specify the Hugo version you want to use

    - name: Build Hugo site
      run: hugo

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: './public'  # Path to the directory containing the generated site
        publish_branch: gh-pages  # Branch to deploy the site to